/**
 * Core data types for the creative assistant.
 *
 * Design principles:
 * - Images are always referenced by ID, never stored inline as base64.
 * - Conversation history stays small by using image references like [image:id].
 * - All timestamps are Unix milliseconds for IndexedDB indexing.
 */

/** Top-level container. A game, a story, a visual exploration. */
export interface Project {
	id: string;
	name: string;
	description: string;
	createdAt: number;
	updatedAt: number;
}

/** A conversation thread within a project. */
export interface Conversation {
	id: string;
	projectId: string;
	title: string;
	createdAt: number;
	updatedAt: number;
}

/** Role in a conversation turn. */
export type MessageRole = 'user' | 'assistant';

/**
 * A single message in a conversation.
 *
 * The text field may contain image references like [image:abc123] which
 * get resolved to object URLs at render time.
 */
export interface Message {
	id: string;
	conversationId: string;
	role: MessageRole;
	text: string;
	/** IDs of images generated or attached in this message. */
	imageIds: string[];
	createdAt: number;
}

/** Whether an image was uploaded by the user or generated by the AI. */
export type ImageSource = 'user' | 'generated';

/** Image metadata, stored separately from heavy blob data. */
export interface ImageMeta {
	id: string;
	projectId: string;
	/** The message that produced this image, if any. */
	messageId?: string;
	source: ImageSource;
	mimeType: string;
	width?: number;
	height?: number;
	/** Human-readable label assigned by the agent or user. */
	label: string;
	/** The prompt or context that produced this image. */
	generationContext?: string;
	createdAt: number;
}

/** Heavy blob data, loaded on demand. */
export interface ImageBlob {
	id: string;
	blob: Blob;
	/** Downscaled version (max 512px) for sending to the model as context. */
	thumbnail: Blob;
}


/** Per-project knowledge produced and consumed by the agent. */
export interface AgentMemory {
	id: string;
	projectId: string;
	/** Agent-assigned, unique per project, e.g. "art-style". */
	slug: string;
	title: string;
	/** 1-2 sentences shown in the system prompt index. */
	summary: string;
	/** Full markdown body, fetched on demand via read_memory. */
	content: string;
	createdAt: number;
	updatedAt: number;
}

/** App-level settings persisted in IndexedDB. */
export interface Settings {
	id: 'app';
	geminiApiKey?: string;
}

export const DEFAULT_SETTINGS: Settings = {
	id: 'app',
	geminiApiKey: undefined
};

/** Hardcoded model IDs. Not user-configurable. */
export const TEXT_MODEL = 'gemini-3-flash-preview';
export const IMAGE_MODEL = 'gemini-3.1-flash-image-preview';
