import type { Content } from '@google/genai';

/**
 * Core data types for the creative assistant.
 *
 * Design principles:
 * - Images are always referenced by ID, never stored inline as base64.
 * - Conversations store two parallel representations: ChatMessage records
 *   for UI display, and a raw Gemini Content[] (apiHistory) for API
 *   continuity. The two are populated independently and never derived
 *   from each other.
 * - All timestamps are Unix milliseconds for IndexedDB indexing.
 */

/** Top-level container. A game, a story, a visual exploration. */
export interface Project {
	id: string;
	name: string;
	description: string;
	createdAt: number;
	updatedAt: number;
}

/**
 * A conversation thread within a project.
 *
 * Chat messages (ChatMessage[]) and API history (apiHistory) are stored
 * separately. Messages are the UI-facing representation; apiHistory
 * preserves the full Gemini protocol state (tool calls, thought
 * signatures, inline thumbnails) needed to continue the session.
 */
export interface Conversation {
	id: string;
	projectId: string;
	title: string;
	/** Gemini Content[] for API continuity. Includes tool call/response structure and thought signatures. */
	apiHistory: Content[];
	createdAt: number;
	updatedAt: number;
}

export type ChatMessageRole = 'user' | 'assistant';

/**
 * UI-facing record for a single chat message. Stores human-readable text
 * with [image:id] references resolved at render time. Not used for API
 * calls; see Conversation.apiHistory for that.
 */
export interface ChatMessage {
	id: string;
	conversationId: string;
	role: ChatMessageRole;
	text: string;
	/** IDs of images generated or attached in this message. */
	imageIds: string[];
	/** If true, this message belongs to a turn that ended in error.
	 *  The model may not have full context of these messages.
	 *  Error-turn messages are deleted when the next turn begins. */
	errorTurn?: boolean;
	createdAt: number;
}

/** Whether an image was uploaded by the user or generated by the AI. */
export type ImageSource = 'user' | 'generated';

/** Image metadata and thumbnail, stored separately from the full-size blob. */
export interface ImageMeta {
	id: string;
	projectId: string;
	/** The message that produced this image, if any. */
	messageId?: string;
	source: ImageSource;
	mimeType: string;
	width?: number;
	height?: number;
	/** Human-readable label assigned by the agent or user. */
	label: string;
	/** The prompt or context that produced this image. */
	generationContext?: string;
	/** Downscaled JPEG (max 512px) for gallery display and model context. */
	thumbnail: Blob;
	createdAt: number;
}

/** Full-size image blob, loaded on demand. */
export interface ImageBlob {
	id: string;
	blob: Blob;
}


/** Per-project knowledge produced and consumed by the agent. */
export interface AgentMemory {
	id: string;
	projectId: string;
	/** Agent-assigned, unique per project, e.g. "art-style". */
	slug: string;
	title: string;
	/** 1-2 sentences shown in the system prompt index. */
	summary: string;
	/** Full markdown body, fetched on demand via read_memory. */
	content: string;
	createdAt: number;
	updatedAt: number;
}

/** App-level settings persisted in IndexedDB. */
export interface Settings {
	id: 'app';
	geminiApiKey?: string;
}

export const DEFAULT_SETTINGS: Settings = {
	id: 'app',
	geminiApiKey: undefined
};

/** Hardcoded model IDs. Not user-configurable. */
export const TEXT_MODEL = 'gemini-3-flash-preview';
export const IMAGE_MODEL = 'gemini-3.1-flash-image-preview';
